[package]
name = "procedural_nannou"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.11"
nannou = "0.18.1"
nom = "7.1.3"
rand = "0.8.5"
